### PR TITLE
Added verification when logging in

### PR DESCRIPTION
**Pull request by Raqkkkkk**
Added verification screen when logging in.

Verification is done by moving a slider to rotate an image to its upright position. After rotating it also displays some stats (time starts from when the user starts to move the slider and percentage stat is just based on a predetermined normal distribution that has no basis whatsoever).
The verification passes as long as the image is within ±20 degrees from its upright position.

Images for verification are in the `./verifyimages` folder, and an image in it is randomly chosen through the createverification use case every verification.

### CODE REVIEW

**Review by Justinfan591 — APPROVED** [review]
Solid

**Comment by Justinfan591** [comment]
What is the use case for this?

**Comment by sherwinokhowat** [comment]
I noticed that for verification you send the time taken to a normal distributed probability calculator. What is the normal distribution constructed upon?

**Comment by Raqkkkkk** [comment]
> What is the use case for this?

I added a create verification use case to access pictures for verification.

**Comment by Raqkkkkk** [comment]
> I noticed that for verification you send the time taken to a normal distributed probability calculator. What is the normal distribution constructed upon?

The mean and standard deviation of the distribution is random decided by me since idk what the actual distribution would be.

**Review by sherwinokhowat — APPROVED** [review]
Really cool stuff.

**Pull request merged**
