### PR TITLE
Increase coverage for local repository tests

### LINKED ISSUE #116: There is an issue for the Test for UserProjectRepositorTest and SearchProjectInteractor
The tests are failing.

### LINKED ISSUE #119: EditProjectInteractorTest failed
`testEditAndSearchProject()` in `EditProjectInteractorTest` has failed. Can someone please resolve it?

### PR DESCRIPTION
**Pull request by Raqkkkkk**
Added read csv file tests to increase coverage for local repositories.
Also fixed some bugs that got discovered with these tests.

### CODE REVIEW

**Comment by Raqkkkkk** [comment]
Also fixed interactor test fails with this request.

**Comment by Justinfan591** [comment]
Seems good to me

**Review by Justinfan591 — APPROVED** [review]
nice

**Review by sherwinokhowat — APPROVED** [review]
Your changes work on my end. Good work.

**Review by cecexyzhang — APPROVED** [review]
Looks good, the tests are more comprehensive now and some errors were also fixed.

**Comment by cecexyzhang** [comment]
Let's merge it after everyone has reviewed and approved. I see that this merge will also address two issues we have raised.

**Comment by Raqkkkkk** [comment]
Merging pull request so that the bug is addressed and we don't get confused by or ignore similar tests errors that might pop up.

**Pull request merged**
