### PR TITLE
add tests for create verification use case

### LINKED ISSUE #125: Tests for create verification use case

### PR DESCRIPTION
**Pull request by Raqkkkkk**
add tests plz review :D

### CODE REVIEW

**Review by Pixeldom4 — APPROVED** [review]
Overall the test classes are well-structured and are comprehensive in coverage. I don't have any recommendations except that you can make test and class names for concise. For example **createVerification_withValidImageFinder_callsVerificationCreated** could be **createVerification_whenImageIsFound_callsVerificationCreated** or something more concise (naming is long, a bit redundant and confusing at times).

**Review by sherwinokhowat — APPROVED** [review]
I think the current naming is fine, although long, and approve of this to be merged. Although, you should probably be sticking with camel case and not including underscores.

**Comment by Raqkkkkk** [comment]
Edited method naming

**Comment by Raqkkkkk** [comment]
merged as suggestions are addressed

**Pull request merged**
