### PR TITLE
fixed database tests

### PR DESCRIPTION
**Pull request by sherwinokhowat**
Fixed the database tests that were occasionally failing and made it so that each database that was created for testing is properly deleted after each test case.

### CODE REVIEW

**Review by Raqkkkkk — CHANGES_REQUESTED** [review]
This still doesn't seem to fix the problem of testing data somehow being created in main database (`projectDatabase.db`) during testing. 
After some debugging I think that the issue is that while testing other classes, the `DataAccessConfig` is accessed (ex. use case factory classes), causing the main database to initialize without closing after the test is finished. Then, the first repository test after it would use the unclosed connection to do tests, which depending on which test it is could cause dummy data to be created on the main database.
From my testing it seems that disconnecting the DatabaseConnection before initializing during the setup of each test would fix this (adding `DatabaseConnection.disconnect()` to the beginning of each `setup()`).

**Comment by sherwinokhowat** [comment]
> This still doesn't seem to fix the problem of testing data somehow being created in main database (`projectDatabase.db`) during testing. After some debugging I think that the issue is that while testing other classes, the `DataAccessConfig` is accessed (ex. use case factory classes), causing the main database to initialize without closing after the test is finished. Then, the first repository test after it would use the unclosed connection to do tests, which depending on which test it is could cause dummy data to be created on the main database. From my testing it seems that disconnecting the DatabaseConnection before initializing during the setup of each test would fix this (adding `DatabaseConnection.disconnect()` to the beginning of each `setup()`).

I think you're right, since some tests use DataAccessConfig directly, which is by default linked to the main database. The static block then initializes the databases since by default the config is set to use the database implementation.

**Comment by sherwinokhowat** [comment]
@Raqkkkkk I have fixed the changes. Please review again.

**Review by Raqkkkkk — APPROVED** [review]
Everything seems good now

**Pull request merged**
